### ISSUE TITLE
Wrong response while calling 'getProcessResults' method

### ISSUE THREAD

**Issue by yadavpeoplelink** [Copyleaks/NodeJS-Plagiarism-Checker#1]
When I call  'getProcessResults' method for any process, it's returning same sample report as shown below - 

[ { URL: 'http://example.com/',
    Percents: 1,
    NumberOfCopiedWords: 1,
    ComparisonReport: 'https://api.copyleaks.com/v1/downloads/comparison?rid=2316758',
    CachedVersion: 'https://api.copyleaks.com/v1/downloads/result-text?rid=2316758',
    Title: 'Example Domain',
    Introduction: 'No introduction available.',
    EmbededComparison: 'https://copyleaks.com/compare-embed/6bd0604a-b28f-442c-b647-13de61acfbe3/2316758' } ]

Please let me know how to get complete Plagiarism report of any processId.

**Comment by Copyleaks** [comment]
Hi, you are working in sandbox mode and this is why you are getting back the same sample report.

Simply delete the line where you add the sandbox header to your request and you will get back real results to your requests.

**Comment by yadavpeoplelink** [comment]
Thanks....Working :+1:  :)
