### ISSUE TITLE
Error Code:13

### ISSUE THREAD

**Issue by praty25** [Copyleaks/NodeJS-Plagiarism-Checker#2]
How can I the know credits required for a particular file so that I can validated it with the total number of credits available in my account and solve error code:13(Unhandled rejection error code: 13 {"Message":"You don't have enough credits to complete the request (required 7 credits)!"})

**Comment by Copyleaks** [comment]
Each credit allows the analysis of up to 250 words. You can simply check the number of words in your document (using Word for example) and split it by 250, which will give you the number of credits you will need to complete the scan.

**Comment by praty25** [comment]
Thanks
