### ISSUE TITLE
ProcessId

### ISSUE THREAD

**Issue by praty25** [Copyleaks/NodeJS-Plagiarism-Checker#3]
1.Does plagiarism-checker charges for creating process id or it only charges for getting plagiarism result?
2.Does plagiarism process Id will be saved in your server for only limited amount of hours?If yes what is the time period?

**Comment by Copyleaks** [comment]
1. The charge is per scan request (using one of the 'create-by' methods) and is based on the volume of the content that is being scannd. One credit allows the analysis of up to 250 words (one page).
2. The process Id will be saved for 90 days. Please check the [technical specification page](https://api.copyleaks.com/GeneralDocumentation/TechnicalSpecifications) for more information.
