### ISSUE TITLE
Callback of 'getProcessResults' is not invoked when error happens

### ISSUE THREAD

**Issue by mwcshao** [Copyleaks/NodeJS-Plagiarism-Checker#7]
When I invoke `getProcessResults(_pid, callback)` to get the final result (the `getProcessStatus` API call returned 'finish' and '100%' progress), the callback is never invoked.

I looked into the source code and find the possible root cause is in `API.prototype.executeAPI` function of API.js file -- if something wrong happens, the `API.prototype.errorHandler()` invocation inside above function would lead to an error thrown, which prevents the callback invocation forever.

If the root cause is confirmed, I'm glad to raise a Pull Request.

**Comment by elir-copyleaks** [comment]
Hi @mwcshao, would you please try to see if the error is available in the promise returned form executeAPI?
```
api.executeAPI(options,cb).then(
      function(response){
      }).catch(function(response){
          //error will be thrown here
});
```

Thanks, Eli.

**Comment by elir-copyleaks** [comment]
Yes @mwcshao, A Pull Request will be more than welcome for this issue.

**Comment by mwcshao** [comment]
Hi, @elir-copyleaks. Yes, I can see the error at the place "//error will be thrown here". I'll create a Pull Request soon.

**Comment by elir-copyleaks** [comment]
Thanks @mwcshao.
